//! `[[ string =~ ere ]]` — the one conditional operator with a regular-expression engine behind
//! it, and the one that writes back into the environment.
//!
//! Before this existed, `=~` fell through `eval_binary`'s catch-all and was **always false**. That
//! is the worst possible answer for the operator's dominant use, input validation: every
//! `[[ $v =~ ^[0-9]+$ ]] || die` guard reported "not a number" for `42`, and every guard written
//! the other way round (`if [[ $v =~ ... ]]; then use it; fi`) silently skipped the good path. The
//! failure was invisible because `[[` still exited 1, which is a legitimate answer.
//!
//! Two things this module owns that the rest of the operator table does not need:
//!
//! * **Pattern versus literal.** In `[[ ]]`, quoting the right operand turns off its special
//!   meaning — `[[ abc =~ "a.c" ]]` is false, because the quoted text is matched as ordinary
//!   characters. rush decides this the same way it decides `==` versus `=`: the adapter looks at
//!   the *source* quoting and emits a different operator word. [`REGEX_OP`] is the unquoted
//!   (pattern) spelling, [`REGEX_LITERAL_OP`] the quoted one.
//! * **`BASH_REMATCH`.** A successful match publishes the whole match at index 0 and each capture
//!   group after it; a failed match leaves an empty array behind, as bash does. An *invalid*
//!   regular expression leaves the previous contents alone and exits 2 — it is a syntax error, not
//!   a negative answer.

use super::operators::{TestError, TestResult};
use crate::env::scope::{Environment, ShellArray};
use regex::{Regex, RegexBuilder};

/// The operator word the adapter emits when the right operand was **unquoted**: an ERE.
pub(super) const REGEX_OP: &str = "=~";

/// The operator word the adapter emits when the right operand was **quoted**, so its text is
/// matched literally.
///
/// Deliberately unspellable in real shell syntax: `[[` is generated by
/// [`crate::parser::brush_adapter`], never written by a user, and a spelling bash would accept
/// would let a script reach the literal form while claiming to use the pattern form. It mirrors
/// the existing `==` (pattern) / `=` (literal) pair, which the adapter picks between using the
/// same source-quoting test.
pub(super) const REGEX_LITERAL_OP: &str = "=~lit";

/// Whether `op` is one of the two regex spellings.
///
/// Used to route *before* [`super::operators::eval_binary`], which cannot do this job: matching
/// needs `&mut Environment` to publish `BASH_REMATCH`, and the POSIX grammar that shares that
/// table only has `&Environment`. Keeping `=~` out of `is_binary_op` is also what makes
/// `[ a =~ b ]` report `=~: binary operator expected` and exit 2, exactly as bash does — `=~` is
/// a `[[ ]]`-only operator.
pub(super) fn is_regex_op(op: &str) -> bool {
    op == REGEX_OP || op == REGEX_LITERAL_OP
}

/// Evaluate `subject =~ operand`, updating `BASH_REMATCH`.
pub(super) fn eval_regex_match(
    env: &mut Environment,
    subject: &str,
    op: &str,
    operand: &str,
) -> TestResult<bool> {
    let source = if op == REGEX_LITERAL_OP {
        regex::escape(operand)
    } else {
        operand.to_string()
    };

    let re = compile(&source)?;

    // `find`, not `is_match`, because the captures are the point: the caller reads them back out
    // of BASH_REMATCH.
    let Some(caps) = re.captures(subject) else {
        // bash clears BASH_REMATCH on a failed match rather than leaving the last success in
        // place, so a script cannot read a stale group and believe it matched.
        env.set_array("BASH_REMATCH", ShellArray::default());
        return Ok(false);
    };

    // A group that took part in no alternative is the empty string, not a missing element:
    // `[[ ab =~ (a)(x)?(b) ]]` leaves `${#BASH_REMATCH[@]}` at 4 in bash, with element 2 empty.
    let groups = (0..caps.len()).map(|i| caps.get(i).map_or("", |m| m.as_str()));
    env.set_array("BASH_REMATCH", ShellArray::from_values(groups));
    Ok(true)
}

/// Compile an ERE the way bash's `regcomp` does, or fail with bash's diagnostic.
fn compile(source: &str) -> TestResult<Regex> {
    RegexBuilder::new(source)
        // POSIX `.` matches every character including newline; the regex crate's default excludes
        // it. `[[ $'a\nb' =~ a.b ]]` is true in bash, and now here too.
        .dot_matches_new_line(true)
        // `^`/`$` anchor the whole subject, never a line within it — the crate's default, pinned
        // here so a future default change cannot quietly turn `^[0-9]+$` into a per-line test.
        .multi_line(false)
        .build()
        .map_err(|_| {
            TestError::new(format!(
                "invalid regular expression `{}'",
                truncate_for_message(source)
            ))
        })
}

/// Keep a runaway pattern from filling the terminal; the point of the message is which expression
/// was rejected, and a long one is recognisable from its first line.
fn truncate_for_message(source: &str) -> String {
    const LIMIT: usize = 120;
    match source.char_indices().nth(LIMIT) {
        Some((cut, _)) => format!("{}...", &source[..cut]),
        None => source.to_string(),
    }
}

#[cfg(test)]
mod tests;
